---
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: labos
spec:
  api:
    sans:
      - kubernetes.labos.local
    extraArgs:
      admission-control-config-file: /etc/admission.yaml
      # oidc-issuer-url: <issuer-url>
      # oidc-client-id: <client-id>
      # oidc-username-claim: email # we use email token claim field as a username
  network:
    provider: custom
    # podCIDR: 10.244.0.0/16
    # serviceCIDR: 10.96.0.0/12
    # dualStack:
    #   enabled: false
    #   IPv6podCIDR: fd00::/108
    #   IPv6serviceCIDR: fd01::/108
    # controlPlaneLoadBalancing:
    #   enabled: false
    #   type: Keepalived
    #   keepalived:
    #     vrrpInstances: []
    #     # - virtualIPs: ["192.168.122.200/24"]
    #     #   authPass: Example
    #     virtualServers: []
    #     # - ipAddress: "<External ip address>"
    # nodeLocalLoadBalancing:
    #   enabled: false
    #   type: EnvoyProxy
  featureGates:
    - name: KubeletInUserNamespace
      enabled: true
    - name: UserNamespacesSupport
      enabled: true
    - name: UserNamespacesPodSecurityStandards
      enabled: false
  extensions:
    helm:
      charts:
        - name: cilium
          chartname: cilium/cilium
          namespace: kube-system
          order: 1
          version: 1.16.2
          values: |
            gatewayAPI:
              enabled: true
            operator:
              replicas: 1
            kubeProxyReplacement: true
        - name: openebs
          chartname: openebs/openebs
          namespace: kube-system
          order: 1
          version: 3.10.0
          values: |
            analytics:
              enabled: false
            localprovisioner:
              hostpathClass:
                isDefaultClass: true
        - name: cert-manager
          chartname: jetstack/cert-manager
          namespace: cert-manager
          order: 2
          version: v1.16.0
          values: |
            crds:
              enabled: true
        - name: capi-operator
          chartname: oci://registry-1.docker.io/sanselmechart/capi-operator
          namespace: operators
          order: 3
          version: 0.13.0
          values: |
            replicaCount: 1
            resources:
              manager:
                limits: {}
                requests: {}
        - name: capi-provider
          chartname: oci://registry-1.docker.io/sanselmechart/capi-provider
          namespace: ucp
          order: 4
          version: 0.1.1
          values: |
            bootstrap: k0sproject-k0smotron:v1.1.2
            controlPlane: k0sproject-k0smotron:v1.1.2
            core: cluster-api:v1.8.3
            infrastructure: docker:v1.8.3;k0sproject-k0smotron:v1.1.2
            manager:
              featureGates:
                core:
                  ClusterTopology: true
                  MachinePool: true
                docker:
                  ClusterTopology: true
                  MachinePool: true
        - name: capi-cluster-class
          chartname: oci://registry-1.docker.io/sanselmechart/capi-cluster-class
          namespace: sre
          order: 6
          version: 0.1.8
          values: |
            kubeadm:
              enabled: false
            k0s:
              enabled: true
              args:
                - --no-taints
                - --enable-worker
            docker:
              enabled: true
      repositories:
        - name: cilium
          url: https://helm.cilium.io/
        - name: jetstack
          url: https://charts.jetstack.io/
        - name: openebs
          url: https://openebs.github.io/charts/
  telemetry:
    enabled: false
