network:
  version: 2
  ethernets:
    oam:
      accept-ra: true
      dhcp4: true
      dhcp6: true
      mtu: 1500
      set-name: oam
      match:
        macaddress: ""
      dhcp4-overrides:
        route-metric: 0
      dhcp6-overrides:
        route-metric: 0
