name: Continuos Integration

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: read-all

jobs:
  bot:
    uses: anselmes/cicd/.github/workflows/bot.yml@d432be297b0bd273290f1f27597fcae874705551 # main https://github.com/anselmes/cicd/commit/d432be297b0bd273290f1f27597fcae874705551
    permissions:
      issues: write
      pull-requests: write
      repository-projects: write
  trivy:
    uses: anselmes/cicd/.github/workflows/trivy.yml@d432be297b0bd273290f1f27597fcae874705551 # main https://github.com/anselmes/cicd/commit/d432be297b0bd273290f1f27597fcae874705551
    permissions:
      contents: write
      id-token: write
      security-events: write
  scorecard:
    uses: anselmes/cicd/.github/workflows/scorecard.yml@d432be297b0bd273290f1f27597fcae874705551 # main https://github.com/anselmes/cicd/commit/d432be297b0bd273290f1f27597fcae874705551
    permissions:
      actions: read
      attestations: read
      checks: read
      contents: read
      deployments: read
      discussions: read
      id-token: write
      issues: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: write
      statuses: read
  # sonarqube:
  #   uses: anselmes/cicd/.github/workflows/sonarqube.yml@d432be297b0bd273290f1f27597fcae874705551 # main https://github.com/anselmes/cicd/commit/d432be297b0bd273290f1f27597fcae874705551
